# Generated by Django 4.1 on 2022-08-07 15:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profile", options={"ordering": ["-joined"]},
        ),
        migrations.AddField(
            model_name="profile",
            name="joined",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
