# Generated by Django 4.1 on 2022-08-07 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_alter_profile_options_profile_joined"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="is_writer",),
        migrations.AddField(
            model_name="profile",
            name="is_writer",
            field=models.BooleanField(default=False),
        ),
    ]
