# Generated by Django 4.1 on 2022-08-14 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_profile_views"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="username",
            field=models.CharField(default="", max_length=50),
            preserve_default=False,
        ),
    ]
