# Generated by Django 4.1 on 2022-08-20 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0008_profile_course_alter_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="slug",
            field=models.SlugField(default="", max_length=30, unique=True),
            preserve_default=False,
        ),
    ]
