# Generated by Django 4.1 on 2022-08-06 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField(max_length=1500)),
                (
                    "slug",
                    models.SlugField(blank=True, max_length=30, null=True, unique=True),
                ),
                ("views", models.BigIntegerField()),
                ("image", models.ImageField(upload_to="")),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Ec", "Economy"),
                            ("FI", "Finance"),
                            ("Po", "Politics"),
                            ("TE", "Technology"),
                            ("Sp", "Sports"),
                            ("uni", "University"),
                            ("Me", "Media"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("published", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("date", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "post",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="content.article",
                    ),
                ),
            ],
        ),
    ]
