# Generated by Django 4.1 on 2022-08-19 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0005_becomewriter_accepted_becomewriter_course_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="becomewriter",
            name="field",
            field=models.CharField(
                choices=[
                    ("Economy", "Economy"),
                    ("Finance", "Finance"),
                    ("Politics", "Politics"),
                    ("Technology", "Technology"),
                    ("Sports", "Sports"),
                    ("Uni", "University"),
                    ("Media", "Media"),
                ],
                default="",
                max_length=50,
            ),
            preserve_default=False,
        ),
    ]
