# Generated by Django 4.1 on 2022-09-17 18:07

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0007_alter_becomewriter_univeristy"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article", name="description", field=tinymce.models.HTMLField(),
        ),
    ]
