# Generated by Django 4.1 on 2022-09-17 18:10

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0008_alter_article_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="description",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
